In [54]:
import torch
import numpy as np

In [55]:
torch.__version__

'2.11.0+cpu'

In [56]:
scalar=torch.tensor(8) #0 dimension tensor
#scalar
scalar.ndim # check dimension
scalar.item() # returns the number from the tensor

# Vector
vector = torch.tensor([7, 7])
vector.ndim
# Check shape of vector
print(vector.shape)


matrix= torch.tensor([[7, 8], [9, 10]])
m= np.array([[7, 7], [8, 8]])

print(m)
print(matrix)
print(matrix.ndim, m.ndim)

tensor= torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])

print(tensor.ndim)
print(tensor.shape) #That means there's 1 dimension of 3 by 3.



torch.Size([2])
[[7 7]
 [8 8]]
tensor([[ 7,  8],
        [ 9, 10]])
2 2
3
torch.Size([1, 3, 3])


Name | What is it? | Number of dimensions | Lower or upper (usually/example)

scalar | a single number | 0 | Lower (a)

vector | a number with direction (e.g. wind speed with direction) but can also have many other 

numbers | 1 | Lower (y)

matrix | a 2-dimensional array of numbers | 2 | Upper (Q)

tensor | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a 
scalar, a 1-dimension tensor is a vector | Upper (X)

In [57]:
# scalar= 7

# vector= [7, 7] or: [7,
#                     7]

# matrix=   [7  10]
#           [7   7]
#           [7   7]

# tensor= [[7,7], [7,7]]
#         [[7,7], [7,7]]
#         [[7,7], [7,7]]


In [58]:
random_tensor= torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.ndim)

random_image_tensor= torch.rand(size=(3, 224, 224))
print(random_image_tensor)
print(random_image_tensor.shape)
print(random_image_tensor.ndim)

zeros= torch.zeros(size=(3,4)) #masking
print(zeros)

tensor([[0.8845, 0.9034, 0.8175, 0.4345],
        [0.9666, 0.6337, 0.6875, 0.0510],
        [0.4873, 0.7557, 0.2179, 0.8922]])
2
tensor([[[0.9680, 0.1595, 0.2710,  ..., 0.4911, 0.0897, 0.3135],
         [0.7456, 0.6884, 0.9054,  ..., 0.3642, 0.7873, 0.1247],
         [0.5564, 0.2032, 0.0378,  ..., 0.3858, 0.7336, 0.4111],
         ...,
         [0.9263, 0.1012, 0.7470,  ..., 0.3557, 0.8123, 0.6669],
         [0.2179, 0.7728, 0.8505,  ..., 0.9438, 0.5984, 0.6830],
         [0.3352, 0.4326, 0.2303,  ..., 0.6701, 0.8187, 0.6194]],

        [[0.6368, 0.6929, 0.4436,  ..., 0.3973, 0.7536, 0.1436],
         [0.6285, 0.2326, 0.1247,  ..., 0.6869, 0.3978, 0.7913],
         [0.6122, 0.9112, 0.6117,  ..., 0.9158, 0.3170, 0.5780],
         ...,
         [0.4235, 0.3592, 0.9316,  ..., 0.9573, 0.1148, 0.0871],
         [0.0600, 0.8766, 0.2981,  ..., 0.9863, 0.6161, 0.0858],
         [0.6008, 0.1688, 0.5604,  ..., 0.3881, 0.7218, 0.2082]],

        [[0.7431, 0.2616, 0.9854,  ..., 0.9644, 0.7450, 0.3

In [59]:
# ranges


ranges= torch.arange(1, 10, 1)
print(ranges)

# create same shape tensor

tensor_zeros= torch.zeros_like(random_image_tensor) #mask random_image_tesor with zeros
tensor_zeros

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [60]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Tensor dtypes

In [61]:
float_16_tensor= torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_16_tensor.dtype

torch.float16

Information on tensors (errors är oftast relaterade till shape, dtype eller device)

In [62]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3780, 0.0846, 0.0396, 0.6697],
        [0.3127, 0.4866, 0.0958, 0.0875],
        [0.4169, 0.0807, 0.2634, 0.0306]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Manipulating tensors (tensor operations) 

In [63]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)

print(tensor * 10) #tensor values dont change unless they are assigned tensor= tensor *3
tensor = tensor - 10
print(tensor)
tensor = tensor + 10
print(tensor)

#built in functions:

tensor= torch.add(tensor, 10)
print(tensor)
tensor= torch.sub(tensor, 10)
#torch.mul
#more common to use operator * 
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

# MATRIX MULTIPLICATION (THE MOST COMMON OPERATION) torch.matmul()

# RULES FOR MATRIX MUL: 
#1. INNER DIMENSIONS MUST MATCH:

#(3, 2) @ (3, 3) WONT WORK
# (3,3) @ (3,3) WILL WORK

#3. THE RESULT OF MATIX MUL WILL BE THE SHAPE OF THE OUTER DIMENSIONS:

# (1, 3) @ (3, 1) = (1, 1), @ =  PYTHONS MATRIX MUL

#element wise:
print('\n',tensor * tensor)


#matrix mul
print(tensor.matmul(tensor))



tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])

 tensor([1, 4, 9])
tensor(14)


MOST COMMON ERRORS IN DEEP LEARNNG (SHAPE ERRORS)

In [64]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


print(tensor_A.shape, tensor_B.shape)
torch.matmul(tensor_A, tensor_B) # (this will error)

torch.Size([3, 2]) torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T   #.T = transpose 1 solution
                       # torch.transpose(tensor_B, dim0, dim1) 2 solution

print(torch.transpose(tensor_B, 0, 1)) #troanspose ändrar struktur på matrisen, byter plats? (T)

print(torch.mm(tensor_A, tensor_B))



tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [109]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
tensor_A=tensor_A.T

torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")



Input shape: torch.Size([2, 3])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])



Finding the min, max, mean, sum, etc (aggregation)
- aggregate them (go from more values to less values)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)


print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(x.dtype)
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
torch.int64
Mean: 45.0
Sum: 450


positional min max

In [120]:
tensor= torch.arange(0,100, 10, dtype=torch.float32)

print(tensor.dtype)
print(tensor.argmax())
print(tensor.argmin())

tensor= tensor.type(torch.float16)

print(tensor.dtype)


torch.float32
tensor(9)
tensor(0)
torch.float16



Reshaping, stacking, squeezing and unsqueezing

In [157]:
tensor= torch.arange(0, 10)
print(tensor.shape)
print(tensor)

#extra dimension

tensor=tensor.reshape(1, 10)

print(tensor.shape)
print(tensor)


x=tensor
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
#x_stacked


print(f"Previous tensor: {x}")
print(f"Previous shape: {x.shape}")
# Remove extra dimension from x_reshaped
x_squeezed = x.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([10])
Previous tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([10])

New tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 10])
