In [3]:
import torch
import numpy as np

In [4]:
torch.__version__

'2.11.0+cpu'

In [5]:
scalar=torch.tensor(8) #0 dimension tensor
#scalar
scalar.ndim # check dimension
scalar.item() # returns the number from the tensor

# Vector
vector = torch.tensor([7, 7])
vector.ndim
# Check shape of vector
print(vector.shape)


matrix= torch.tensor([[7, 8], [9, 10]])
m= np.array([[7, 7], [8, 8]])

print(m)
print(matrix)
print(matrix.ndim, m.ndim)

tensor= torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])

print(tensor.ndim)
print(tensor.shape) #That means there's 1 dimension of 3 by 3.



torch.Size([2])
[[7 7]
 [8 8]]
tensor([[ 7,  8],
        [ 9, 10]])
2 2
3
torch.Size([1, 3, 3])


Name | What is it? | Number of dimensions | Lower or upper (usually/example)

scalar | a single number | 0 | Lower (a)

vector | a number with direction (e.g. wind speed with direction) but can also have many other 

numbers | 1 | Lower (y)

matrix | a 2-dimensional array of numbers | 2 | Upper (Q)

tensor | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a 
scalar, a 1-dimension tensor is a vector | Upper (X)

In [6]:
# scalar= 7

# vector= [7, 7] or: [7,
#                     7]

# matrix=   [7  10]
#           [7   7]
#           [7   7]

# tensor= [[7,7], [7,7]]
#         [[7,7], [7,7]]
#         [[7,7], [7,7]]


In [7]:
random_tensor= torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.ndim)

random_image_tensor= torch.rand(size=(3, 224, 224))
print(random_image_tensor)
print(random_image_tensor.shape)
print(random_image_tensor.ndim)

zeros= torch.zeros(size=(3,4)) #masking
print(zeros)

tensor([[0.4515, 0.8980, 0.0135, 0.5081],
        [0.2170, 0.5748, 0.3841, 0.2550],
        [0.4711, 0.0322, 0.8154, 0.8129]])
2
tensor([[[3.1971e-01, 7.3452e-01, 3.1150e-01,  ..., 8.8270e-01,
          8.5831e-01, 8.0159e-01],
         [7.9727e-01, 3.5730e-01, 1.5917e-01,  ..., 8.5781e-01,
          9.5781e-02, 8.0958e-01],
         [1.0346e-01, 6.7730e-01, 5.6744e-01,  ..., 4.3450e-01,
          6.8808e-01, 2.2806e-01],
         ...,
         [4.1674e-01, 9.9026e-01, 8.5940e-01,  ..., 4.9319e-01,
          7.5627e-01, 3.8976e-01],
         [5.7231e-01, 3.7984e-01, 6.7340e-01,  ..., 6.7152e-02,
          2.8198e-01, 4.2682e-01],
         [9.4735e-01, 9.3730e-01, 4.2748e-01,  ..., 8.3591e-01,
          1.2361e-01, 3.8212e-03]],

        [[9.3301e-02, 7.6683e-01, 5.9047e-01,  ..., 2.2047e-01,
          4.5615e-01, 3.3631e-01],
         [5.5590e-01, 4.9392e-01, 1.0385e-01,  ..., 6.6960e-01,
          9.9562e-01, 2.1262e-01],
         [1.5267e-01, 8.9069e-01, 2.8242e-01,  ..., 3.5749e-01,

In [8]:
# ranges


ranges= torch.arange(1, 10, 1)
print(ranges)

# create same shape tensor

tensor_zeros= torch.zeros_like(random_image_tensor) #mask random_image_tesor with zeros
tensor_zeros

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [9]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Tensor dtypes

In [10]:
float_16_tensor= torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_16_tensor.dtype

torch.float16

Information on tensors (errors är oftast relaterade till shape, dtype eller device)

In [11]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6327, 0.1667, 0.7466, 0.9010],
        [0.2611, 0.3789, 0.9078, 0.7520],
        [0.4100, 0.8109, 0.9779, 0.5693]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Manipulating tensors (tensor operations) 

In [12]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)

print(tensor * 10) #tensor values dont change unless they are assigned tensor= tensor *3
tensor = tensor - 10
print(tensor)
tensor = tensor + 10
print(tensor)

#built in functions:

tensor= torch.add(tensor, 10)
print(tensor)
tensor= torch.sub(tensor, 10)
#torch.mul
#more common to use operator * 
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

# MATRIX MULTIPLICATION (THE MOST COMMON OPERATION) torch.matmul()

# RULES FOR MATRIX MUL: 
#1. INNER DIMENSIONS MUST MATCH:

#(3, 2) @ (3, 3) WONT WORK
# (3,3) @ (3,3) WILL WORK

#3. THE RESULT OF MATIX MUL WILL BE THE SHAPE OF THE OUTER DIMENSIONS:

# (1, 3) @ (3, 1) = (1, 1), @ =  PYTHONS MATRIX MUL

#element wise:
print('\n',tensor * tensor)


#matrix mul
print(tensor.matmul(tensor))



tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])

 tensor([1, 4, 9])
tensor(14)


MOST COMMON ERRORS IN DEEP LEARNNG (SHAPE ERRORS)

In [13]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


print(tensor_A.shape, tensor_B.shape)
torch.matmul(tensor_A, tensor_B) # (this will error)

torch.Size([3, 2]) torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T   #.T = transpose 1 solution
                       # torch.transpose(tensor_B, dim0, dim1) 2 solution

print(torch.transpose(tensor_B, 0, 1)) #troanspose ändrar struktur på matrisen, byter plats? (T)

print(torch.mm(tensor_A, tensor_B))


#.T 2D flyttar väderna
# .transpose(x,y) flyttar 2 element manuellt, funkar på högre dm också
#.permute(x,y,z) flytta på flera i högre dm

#.mT funkar för högre men vänder bara på dem, 1 2 3 -> 3 2 1

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
tensor_A=tensor_A.T

torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")



Input shape: torch.Size([2, 3])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])



Finding the min, max, mean, sum, etc (aggregation)
- aggregate them (go from more values to less values)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)


print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(x.dtype)
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
torch.int64
Mean: 45.0
Sum: 450


positional min max

In [ ]:
tensor= torch.arange(0,100, 10, dtype=torch.float32)

print(tensor.dtype)
print(tensor.argmax())
print(tensor.argmin())

tensor= tensor.type(torch.float16)

print(tensor.dtype)


torch.float32
tensor(9)
tensor(0)
torch.float16



Reshaping, stacking, squeezing and unsqueezing

In [ ]:
tensor= torch.arange(0, 10)
print(tensor.shape)
print(tensor)

#extra dimension

tensor=tensor.reshape(1, 10)

print(tensor.shape)
print(tensor)


x=tensor
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
#x_stacked


print(f"Previous tensor: {x}")
print(f"Previous shape: {x.shape}")
# Remove extra dimension from x_reshaped
x_squeezed = x.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
x_unsqueezed.ndim

torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([10])
Previous tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([10])

New tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 10])


2

indexing

In [ ]:
X= torch.arange(1, 10).reshape(1,3,3)
print(X, X.shape)

# Let's index bracket by bracket
print(f"First square bracket:\n{X[0]}") 
print(f"Second square bracket: {X[0][0]}") 
print(f"Third square bracket: {X[0][0][0]}")

# Get all values of 0th dimension and the 0 index of 1st dimension
X[:, 0]

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
X[:, :, 1]

# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
X[:, 1, 1]

# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
X[0, 0, :] # same as x[0][0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


tensor([1, 2, 3])

Tensors and numpy

In [ ]:
import numpy as np

array= np.arange(1.0, 8.0)

tensor= torch.from_numpy(array).type(torch.float32)

print(array, tensor)

# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.])


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

reproducability

In [ ]:

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5192, 0.6108, 0.4586, 0.0542],
        [0.4900, 0.8410, 0.6022, 0.4078],
        [0.7967, 0.5757, 0.8226, 0.5136]])

Tensor B:
tensor([[0.4258, 0.4373, 0.7357, 0.7541],
        [0.7176, 0.8726, 0.0257, 0.0524],
        [0.9103, 0.3440, 0.2697, 0.1107]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import random

RANDOM_SEED=42

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

run on gpu if possible

In [ ]:
# Set device type
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
device

'cpu'

EXERCISE!

Create a random tensor with shape (7, 7).

In [ ]:
tensor= torch.rand(size=(7,7))
tensor.shape

torch.Size([7, 7])

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
tensor2= torch.rand(1,7)
print(tensor2.shape)

result= tensor.mm(torch.t(tensor2))
result

torch.Size([1, 7])


tensor([[1.0859],
        [0.8713],
        [1.0421],
        [1.5877],
        [1.3137],
        [1.6848],
        [1.0519]])

Set the random seed to 0 and do exercises 2 & 3 over again.


In [50]:


random_seed= 0
torch.manual_seed(seed=random_seed)
random_tensor1= torch.rand(size=(7,7))

torch.manual_seed(seed=random_seed)
random_tensor2= torch.rand(size=(1,7))


print(random_tensor1)
print(random_tensor2)


tensor1_2= random_tensor2.mm(random_tensor1.T)

print(tensor1_2)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[1.5985, 1.1173, 1.2741, 1.6838, 0.8279, 1.0347, 1.2498]])


Find the maximum and minimum values of the output 

In [54]:
print(random_tensor1.min())
print(random_tensor1.max())
print(random_tensor1.mean())

print(random_tensor1.argmax()) #index där värdet är högst
print(random_tensor1.argmin())#index där värdet är lägst



tensor(0.0223)
tensor(0.9527)
tensor(0.4512)
tensor(26)
tensor(12)


Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [67]:
torch.manual_seed(7)
tens= torch.rand(1,1,1,10)

print(tens)
print(tens.squeeze(0,1,2))

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
