In [1]:
import pandas as pd
import torch

In [2]:
TENSOR= torch.arange(1, 11, dtype=torch.float32)
print(TENSOR)
TENSOR.shape

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


torch.Size([10])

In [3]:
TENSOR.reshape(1, 10)
TENSOR.reshape(5, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [4]:
print(TENSOR)
TENSOR=TENSOR.squeeze()
print(TENSOR)
TENSOR= TENSOR.unsqueeze(dim=1)
print('shape', TENSOR.shape)
print('size', TENSOR.size())
print(TENSOR)



tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
shape torch.Size([10, 1])
size torch.Size([10, 1])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])


STACKING 

In [5]:
print(TENSOR)
print('\n')

print(torch.stack([TENSOR, TENSOR],  ))
print(TENSOR.shape)
print(TENSOR.squeeze().shape)

print(TENSOR.unsqueeze(dim=0).shape)


tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])


tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]],

        [[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]])
torch.Size([10, 1])
torch.Size([10])
torch.Size([1, 10, 1])


rearranging/ permuting

In [6]:
tensor= torch.rand(224,224,3)
print(tensor.shape)

tensor_permuted= tensor.permute(2, 0, 1 )
print(tensor_permuted.shape)

tensor

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


tensor([[[0.3763, 0.2544, 0.9835],
         [0.2234, 0.2627, 0.9446],
         [0.4995, 0.0832, 0.1065],
         ...,
         [0.9229, 0.4004, 0.0699],
         [0.6087, 0.4475, 0.8560],
         [0.9507, 0.9896, 0.9363]],

        [[0.6077, 0.8057, 0.8913],
         [0.4821, 0.3423, 0.9114],
         [0.8865, 0.4065, 0.3102],
         ...,
         [0.2546, 0.9696, 0.1068],
         [0.8075, 0.3070, 0.6076],
         [0.2497, 0.7878, 0.2424]],

        [[0.9987, 0.4932, 0.1558],
         [0.1957, 0.8975, 0.1388],
         [0.6159, 0.9463, 0.4134],
         ...,
         [0.6900, 0.7264, 0.7218],
         [0.1859, 0.7334, 0.3373],
         [0.9961, 0.0453, 0.2492]],

        ...,

        [[0.3351, 0.2069, 0.2689],
         [0.2255, 0.8817, 0.5072],
         [0.3949, 0.6373, 0.3432],
         ...,
         [0.3844, 0.4971, 0.3448],
         [0.4631, 0.9608, 0.6831],
         [0.4073, 0.0262, 0.8724]],

        [[0.6106, 0.5162, 0.3658],
         [0.7232, 0.1425, 0.5085],
         [0.

In [7]:
indexing= torch.arange(1, 10).reshape(1, 3, 3)
print(indexing)


# get all values from 0 dim but only the first index value of the 1 and 2 dimension. 

indexing[:,1, 1]


#get 3, 6, 9

indexing[:, :, 2]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


tensor([[3, 6, 9]])

numpy array torch tensor

In [19]:
import numpy as np

#data from numpy -> tensor: torch.from_numpy(array)
#tensor -> array: torch.Tensor.numpy()

array= np.arange(1.0, 11.0)
print('array:\n', array)

tensor= torch.from_numpy(array).type(torch.float32)
print('new tensor\n', tensor)

#to numpy array:

to_array= torch.Tensor.numpy(tensor)
print('new array:\n', to_array)


array:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
new tensor
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
new array:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Reproduceaility

In [20]:
RANDOMSEED= 42

torch.manual_seed(RANDOMSEED)
tensor= torch.rand(1,9).reshape(1,3,3) # random
#Muste set seed each time using method
torch.manual_seed(RANDOMSEED)
tensor1= torch.rand(1,9).reshape(1,3,3) # random
print(tensor== tensor1)


tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]]])


Running on GPU

In [24]:
device= 'cuda' if torch.cuda.is_available() else 'cpu'


# move tensor to gpu (if available)

tensor= tensor.to(device)
print(tensor.device)

cpu
